name: 🧪 Run Pytest & Generate Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🧱 Install system dependencies for Qt
        run: |
          sudo apt update
          sudo apt install -y libegl1 libgl1 libxcb-xinerama0 libxkbcommon-x11-0

      - name: 🐍 Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 📦 Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html

      - name: 🧪 Run tests and generate report
        run: |
          pytest tests/ --html=report.html --self-contained-html

      - name: 📤 Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html