name: 🧪 Run Pytest & Generate Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 📦 Install runtime dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Install test tools
        run: |
          pip install pytest pytest-html

      - name: 🧪 Run tests and generate HTML report
        run: |
          pytest tests/ --html=report.html --self-contained-html

      - name: 📤 Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html